const mongoose = require('mongoose');
const Schema = mongoose.Schema;

//----database model-----
var productSchema = new Schema({
  Category_type: {type: String},
  Product_Name: {type: String},
  SKU: {type: String},
  Product_Shipping_Weight: {type: Number},
  Product_Shipping_Weight_2: {type: Number},
  Product_Weight: {type: Number},
  Cubic_Feet: {type: Number},
  Color: {type: String},
  Collection: {type: String},
  Number_of_Cartons: {type: Number},
  Packing_Carton_Width: {type: Number},
  Packing_Carton_Depth: {type: Number},
  Packing_Carton_Height: {type: Number},
  Packing_Carton_Width_2: {type: Number},
  Packing_Carton_Depth_2: {type: Number},
  Packing_Carton_Height_2: {type: Number},
  Actual_Product_Length: {type: Number},
  Actual_Product_Width: {type: Number},
  Actual_Product_Height: {type: Number},
  Drawer_Length: {type: String},
  Drawer_Width: {type: String},
  Drawer_height: {type: String},
  Shelf_Length: { type: String },
  Shelf_Width: { type: String },
  Materials: { type: String },
  Product_Description: { type: String },
  Feature_1: { type: String, default:""},
  Feature_2: { type: String, default:""},
  Feature_3: { type: String, default:""},
  Feature_4: { type: String, default:""},
  Feature_5: { type: String, default:""},
  Feature_6: { type: String, default:""},
  Feature_7: { type: String, default:""},
  Feature_8: { type: String, default:""},
  Feature_9: { type: String, default:""},
  Maximum_Shelf_Weight_Capacity: { type: Number },
  Care_Instructions: { type: String },
  Assembly_required: { type: String },
  Product_Shipping_Method: { type: String },
  WxDxH: { type: String },
  Warranty: { type: String },
  Capacity: { type: Number },
  Product_Shipping_Weight_kg: { type: Number },
  Product_Weight_kg: { type: Number },
  Quantity_in_box: { type: Number },
  Package: { type: String },
  Billable_weight: { type: Number },
  Inches_in_between_shelf: { type: Number },
  Mirror_size: { type: String },
  LED: { type: String },
  UV: { type: String },
  Battery_included: { type: String },
  Battery_type: { type: String },
  Wholesale_5_Pad: { type: String },
  Wholesale_10_Pad: { type: String },
  Delivered_Price: { type: String },
  Product_Diameter: { type: Number},
  Retail: { type: Number },
  addDate: {type: Date, default: Date.now()},
  images: {type: String, default: "" },
  active: {type: String, default: "true"},
  Inventory: {type: Number}
})

module.exports = mongoose.model ('Product', productSchema);
